version: '3'
services:
  app:
    image: node:lts-bullseye
    tty: true
    container_name: tts
    working_dir: /app
    entrypoint: ["bash","./docker-entrypoint.sh"]
    volumes:
      - ./:/app
    env_file:
     - ./.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./client_secret.json
    restart: always